### PR TITLE
Feature/bookmarks

### PR DESCRIPTION
**Pull request by 0xdea**
Hey, here's another contribution... Thanks for adding me as an official contributor to the project, by the way!

I've tried to implement a robust bookmarks API that aims to be as usable and sane as possible, even though I had to build it on the cumbersome and almost undocumented API exported by IDA Pro in `include/moves.hpp`. See the notes in `idalib/src/idb.rs` that explain some non-intuitive behaviors, based on my reverse engineering work.

Please reach out to me in case something is unclear or if some modifications are needed.

### CODE REVIEW

**Comment by xorpse** [comment]
Thank you for the PR and the RE work :)! Overall the API and binding code looks good, I think we can make it a bit more idiomatic on the Rust side (I can help do this, just LMK).

The idea I have is to mirror IDA's "bookmarks_t" class, so we'd have an API like this (basically just moves what you had on `IDB` to `Bookmarks`):

On IDB:
```rust
// This gets a "bookmark" manager
pub fn bookmarks<'a>(&'a self) -> Bookmarks<'a> {
    Bookmarks { _marker: PhantomData }
}
```

Then a new module "bookmarks.rs":
```rust
const BOOKMARKS_BAD_INDEX: u32 = 0xffffffff; 

pub struct Bookmarks<'a> {
    _marker: PhantomData<&'a IDB>,
}

pub type BookmarkIndex = u32;

impl<'a> Bookmarks<'a> {
    pub(crate) fn new(_: &'a IDB) -> Self {
        Self { _marker: PhantomData } 
    } 
    
    pub fn mark(...) -> Result<BookmarkIndex, IDAError> {
        ....
    }
    
    pub fn mark_with(...) -> Result<BookmarkIndex, IDAError> {
        ...
    }
    
    // eqivalent to bookmarks_get_descr
    pub fn get_description(&self, ea: Address) -> Option<String> {
    ...
    }
    
    // equivalent to bookmarks_get_descr_with
    pub fn get_description_by_index(&self, idx: BookmarkIndex) -> Option<String> {
        let s = unsafe { idalib_bookmarks_t_get_desc(idx.into()) };
        if s.is_empty() {
            None
         } else {
             Some(s)
         } 
    }
    
    pub fn erase(&self, ea: Address) -> Result<(), IDAError> {
        ...
    }
    
    pub fn erase_by_index(&self, idx: BookmarkIndex) -> Result<(), IDAError> {
        ....
    }
    
    // same as bookmarks_find_index, but we just use None if we don't find a bookmark
    pub fn find_index(&self, ea: Address) -> Option<BookmarkIndex> {
        ....
    }
    
    // bookmarks_size
    pub fn len(&self) -> usize {
        ....
    }
}
```

**Comment by 0xdea** [comment]
Thanks for your feedback! You're absolutely right, it would look much better. I'll give it a shot in the next days.

**Comment by 0xdea** [comment]
It's done already. While I was at it I also made a small improvement to the comment API. Let me know if more work is required. Cheers!

**Comment by xorpse** [comment]
Thank you--it just required a few tweaks so I've merged it--I'll make a release a bit later in the week as I want to finalise a couple more features (initial hexrays support and some features to make IDA respect `enable_console_messages(false)`, rather than printing "Auto analysis completed" no matter what) first.

Also, feel free to submit a PR updating the README with links to any projects you have building on top of idalib :).

**Comment by 0xdea** [comment]
Awesome! About the new features: 
* A nice thing to have would be the printing of license-related error messages (e.g., `Cannot continue without a valid license -> OK`) even with `enable_console_messages(false)`. Currently, I found no way to report IDA license problems to users other than temporarily enabling console messages, and it's not pretty.
* I've been waiting for hexrays support to land into main. I've noticed your project [here](https://github.com/xorpse/wegglir) (thanks for linking to my weggli pattern repo BTW) and I'm planning to port [another one](https://github.com/0xdea/ghidra-scripts/blob/main/Haruspex.java) of my Ghidra scripts to idalib.

I'll submit a PR to update the README with a link to my rhabdomancer idalib port, I think it's mature enough. Thanks again for this project, looking forward to contributing more in the future.

**Comment by xorpse** [comment]
> A nice thing to have would be the printing of license-related error messages

I agree--I took a look at what IDA is doing internally, I think we can implement a variation of the checking logic performed via `init_database`. Currently, when the license check fails, IDA will terminate the process (with or without messages depending on logging), which isn't nice behaviour for a library at all :). Fortunately, `libida` exports `get_license_manager`, which gives us an instance of a class that we can use to check license status, so I think we can provide a function like `is_valid_license` that can be called before we attempt to open a database so the error can be handled programmatically.

> I've been waiting for hexrays support to land into main.

Given the scale of the task, I'll first just export the bare minimum (basically what's there now) so we can get pseudocode, and then work on the ctree API, so the release should be done later today/tomorrow.

> I've noticed your project [here](https://github.com/xorpse/wegglir) (thanks for linking to my weggli pattern repo BTW) and I'm planning to port [another one](https://github.com/0xdea/ghidra-scripts/blob/main/Haruspex.java) of my Ghidra scripts to idalib.

Your patterns are great, by the way! I think your other tool should be straightforward to port with the initial hexrays support. This "wegglir" tool is basically a quality of life improvement for weggli (based on similar experiences to the pain points highlighted in your [past blog](https://security.humanativaspa.it/a-collection-of-weggli-patterns-for-c-cpp-vulnerability-research/))--it adds a ruleset language to help with rule management, and interfaces with idalib so psuedocode can be checked with weggli rules. I'll try to port all of your rules before I release it properly.

**Comment by 0xdea** [comment]
> Fortunately, `libida` exports `get_license_manager`, which gives us an instance of a class that we can use to check license status, so I think we can provide a function like `is_valid_license` that can be called before we attempt to open a database so the error can be handled programmatically.

This looks very promising. I'll let you know in case I'm able to take a stab at implementing this additional functionality.

> Given the scale of the task, I'll first just export the bare minimum (basically what's there now) so we can get pseudocode, and then work on the ctree API, so the release should be done later today/tomorrow.

Sounds good!

> Your patterns are great, by the way! I think your other tool should be straightforward to port with the initial hexrays support. This "wegglir" tool is basically a quality of life improvement for weggli (based on similar experiences to the pain points highlighted in your [past blog](https://security.humanativaspa.it/a-collection-of-weggli-patterns-for-c-cpp-vulnerability-research/))--it adds a ruleset language to help with rule management, and interfaces with idalib so psuedocode can be checked with weggli rules. I'll try to port all of your rules before I release it properly.

Awesome 👍

**Pull request merged**
