### PR TITLE
Misc lint fixes

### PR DESCRIPTION
**Pull request by 0xdea**
After running clippy with some aggressive lints, I made a few minor modifications to the code following some of the recommendations. They seem reasonable to me, hopefully I haven't missed anything crucial. Anyway, none of those are necessary so feel free to reject them of course!

### CODE REVIEW

**Review by xorpse — APPROVED** [review]
Thank you! It probably makes sense for us to adopt clippy as something we run on incoming PRs, or at the very least, a recommended step to take prior to opening a PR. I'll see about adding a workflow for PRs this week.

**Comment by 0xdea** [comment]
Thanks! That would make sense. In the existing codebase, there are still some clippy's recommendations that I haven't implemented, in the following categories:
* needless_lifetimes
* identity_op
* useless_transmute
* missing_transmute_annotations
* missing_safety_doc
* not_unsafe_ptr_arg_deref (looks like a false positive to me)

You might want to take a look at them.

**Comment by xorpse** [comment]
On the dependencies: I don't think we can do much about them right now, as they're inherited via `autocxx-*` and its dependences. E.g., we can bump `windows-sys`, but it doesn't change anything, as we still inherit two versions of `windows-sys`:

```
   = windows-sys v0.52.0
     ├── errno v0.3.9
     │   ├── rustix v0.38.41
     │   │   └── tempfile v3.14.0
     │   │       └── autocxx-engine v0.27.0
     │   │           └── autocxx-build v0.27.0
     │   │               └── (build) idalib-sys v0.2.2+9.0.240925
     │   │                   └── idalib v0.2.2+9.0.240925
     │   ├── rustix v0.38.41 (*)
     │   └── rustix v0.38.41 (*)
     └── rustix v0.38.41 (*)
   = windows-sys v0.59.0
     ├── idalib-sys v0.2.2+9.0.240925
     │   └── idalib v0.2.2+9.0.240925
     ├── tempfile v3.14.0
     │   └── autocxx-engine v0.27.0
     │       └── autocxx-build v0.27.0
     │           └── (build) idalib-sys v0.2.2+9.0.240925 (*)
     └── winapi-util v0.1.9
         └── termcolor v1.4.1
             ├── codespan-reporting v0.11.1
             │   ├── cxx-build v1.0.130
             │   │   └── (build) idalib-sys v0.2.2+9.0.240925 (*)
             │   └── cxx-gen v0.7.130
             │       └── autocxx-engine v0.27.0 (*)
             └── env_logger v0.9.3
                 └── autocxx-build v0.27.0 (*)
```

On clippy: I've addressed the remaining lints that make sense, and silenced the rest. A large majority of issues stem from autogenerated code (`identity_op`) or are due to missing documentation (`missing_safety_doc`)--this should be fixed, I just don't have time right now. On the others, I'm not totally convinced `needless_lifetimes` helps in the context of a project with a lot of unsafe code where we're manipulating lifetimes--I'd opt for more explicitness, since it makes the code a bit easier to reason about (in my opinion). For `not_unsafe_ptr_arg_deref `, I've addressed it-- previously we took a raw pointer as input to a function not marked "unsafe" and then used the pointer assuming it was valid, but since it is the responsibility of the caller to ensure the pointer's validity, it makes more sense for the unsafe block to be at the call-site.

Anyway, thanks for pushing to use clippy!

**Comment by 0xdea** [comment]
> On the dependencies: I don't think we can do much about them right now, as they're inherited via `autocxx-*` and its dependences. E.g., we can bump `windows-sys`, but it doesn't change anything, as we still inherit two versions of `windows-sys`:

Yeah, I thought that would be the case. No biggie in any case.

> On clippy: I've addressed the remaining lints that make sense, and silenced the rest. A large majority of issues stem from autogenerated code (`identity_op`) or are due to missing documentation (`missing_safety_doc`)--this should be fixed, I just don't have time right now. On the others, I'm not totally convinced `needless_lifetimes` helps in the context of a project with a lot of unsafe code where we're manipulating lifetimes--I'd opt for more explicitness, since it makes the code a bit easier to reason about (in my opinion). For `not_unsafe_ptr_arg_deref `, I've addressed it-- previously we took a raw pointer as input to a function not marked "unsafe" and then used the pointer assuming it was valid, but since it is the responsibility of the caller to ensure the pointer's validity, it makes more sense for the unsafe block to be at the call-site.

I agree with everything. At the moment, documentation is indeed lacking. However, I don't think it's an urgent matter... The code is self-explanatory enough even for inexperienced Rust developers (me!) to chime in and submit some PRs so no pressure 😉

**Pull request merged**
