### PR TITLE
Add "license manager" API

### PR DESCRIPTION
**Pull request by xorpse**
This PR provides a mechanism to check if the IDA license idalib has available is valid or not. This allows us to avoid exiting without the possibility to gracefully handle the case of a missing/invalid license when calling `open_database` and `init_database`.

Changes in detail:
- Adds `IDAError::InvalidLicense` and returns it from `open_database`, `IDB::open{,_with}`, etc.
- Adds `LicenseId` with a `Display` implementation matching IDA's formatting, `idalib::license_id`, and `idalib::is_valid_license`.

The implementation of this functionality is based on a small amout of RE of libida (9.0.240925). It has been tested on MacOS (Apple Silicon) and Linux (x86-64), and everything behaves as expected for named licenses (with a missing license, with a valid license); other license types haven't been tested, but should work.

### CODE REVIEW

**Review by yeggor — APPROVED** [review]

**Comment by 0xdea** [comment]
This is awesome! Did you find documentation on the license manager somewhere or did have to reverse engineer it?

**Comment by xorpse** [comment]
Did you find documentation on the license manager somewhere or did you have to reverse engineer all of it (using IDA on IDA, amirite 😂)?

Unfortunately, we had to reverse it 😬, as usual IDA was a great help understanding IDA 🙃. We basically reimplemented the logic called via `init_database`--there's definitely more functionality tied to the license manager that's not covered in this PR, but hopefully we've reversed enough for now and can revisit it if we need more functionality exposed. 

> BTW, I'm using a floating license, I'll let you know if the functionality works with this license type too.

That will be great, thanks a lot!

**Comment by 0xdea** [comment]
I confirm that license check works also with floating license. Great work!

**Comment by 0xdea** [comment]
Actually, I spoke too soon... I just spotted a problem with floating licenses. If I run `cargo run --example=license_check` when the license server is unreachable, I get an `invalid license!` message back, as it should be. 

However, when the license is in use (for instance, if I have an open IDA Pro session so that there are no further seats available), if I run `cargo run --example=license_check` I get a `segmentation fault`!

I don't have time to investigate the cause now, but I can share a coredump file with you if you want. Here's the backtrace:
```
raptor@fnord idalib % lldb -c /cores/core.23969
(lldb) target create --core "/cores/core.23969"
Core file '/cores/core.23969' (arm64) was loaded.
(lldb) bt
* thread #1, stop reason = ESR_EC_DABORT_EL0 (fault address: 0x0)
  * frame #0: 0x0000000183377348 libsystem_platform.dylib`_platform_memmove + 424
    frame #1: 0x000000010560dd40 libida.dylib`___lldb_unnamed_symbol12173 + 520
    frame #2: 0x000000010560d2d8 libida.dylib`___lldb_unnamed_symbol12162 + 132
    frame #3: 0x000000010565c5d0 libida.dylib`___lldb_unnamed_symbol12618 + 140
    frame #4: 0x000000010565c840 libida.dylib`___lldb_unnamed_symbol12619 + 256
    frame #5: 0x00000001056594f8 libida.dylib`___lldb_unnamed_symbol12592 + 1292
    frame #6: 0x0000000105658af0 libida.dylib`___lldb_unnamed_symbol12590 + 1800
    frame #7: 0x00000001049024e8 license_check`idalib_check_license() at kernwin_extras.h:55:15
    frame #8: 0x0000000104902768 license_check`::cxxbridge1$idalib_check_license() at gen2.cxx:843:10
    frame #9: 0x0000000104901b40 license_check`idalib_sys::ffix::idalib_check_license::he07e34d616378da6 at lib.rs:426:19
    frame #10: 0x0000000104900b54 license_check`idalib_sys::ida::is_license_valid::hd0561d4c1a6b7f55 at lib.rs:843:18
    frame #11: 0x00000001048ffa64 license_check`idalib::license::is_valid_license::h8aa95bfd78d025f5 at license.rs:42:5
    frame #12: 0x00000001048fe104 license_check`license_check::main::hf5f0d7ec106611e3 at license_check.rs:4:9
    frame #13: 0x00000001048ff0f0 license_check`core::ops::function::FnOnce::call_once::h72aee13ba54c6594((null)=(license_check`license_check::main::hf5f0d7ec106611e3 at license_check.rs:3), (null)=<unavailable>) at function.rs:250:5
    frame #14: 0x00000001048fe08c license_check`std::sys::backtrace::__rust_begin_short_backtrace::he77d598060a5138d(f=(license_check`license_check::main::hf5f0d7ec106611e3 at license_check.rs:3)) at backtrace.rs:154:18
    frame #15: 0x00000001048ff47c license_check`std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h85b80b5d5ba017f9 at rt.rs:164:18
    frame #16: 0x00000001049268a0 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once::hf77a1752ba39c45f at function.rs:284:13 [opt]
    frame #17: 0x0000000104926898 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::panicking::try::do_call::hf02556a6b145ecfc at panicking.rs:554:40 [opt]
    frame #18: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::panicking::try::h2bb23dba91be7e3b at panicking.rs:518:19 [opt]
    frame #19: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::panic::catch_unwind::h1844bc6507215052 at panic.rs:345:14 [opt]
    frame #20: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::ha90e2c319598814e at rt.rs:143:48 [opt]
    frame #21: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::panicking::try::do_call::h7de69f625a47132a at panicking.rs:554:40 [opt]
    frame #22: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::panicking::try::h2198f44c68c232f7 at panicking.rs:518:19 [opt]
    frame #23: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 [inlined] std::panic::catch_unwind::h40a34eeb64f44ac6 at panic.rs:345:14 [opt]
    frame #24: 0x0000000104926894 license_check`std::rt::lang_start_internal::h9e88109c8deb8787 at rt.rs:143:20 [opt]
    frame #25: 0x00000001048ff448 license_check`std::rt::lang_start::hc03fb43b50275a76(main=(license_check`license_check::main::hf5f0d7ec106611e3 at license_check.rs:3), argc=1, argv=0x000000016b503728, sigpipe='\0') at rt.rs:163:17
    frame #26: 0x00000001048fe238 license_check`main + 36
    frame #27: 0x0000000182fbe0e0 dyld`start + 2360
```

The culprit seems to be a NULL pointer dereference in this line in `kernwin_extras_h`:
```cpp
  auto nres = manager->_vtbl->borrow_license(manager, field_ptr, &borrow_license_arg3, 16, &ptr);
```

Let me know if I can assist further. Next week I should be able to did deeper into this if needed.

**Comment by xorpse** [comment]
Thanks for thoroughly testing :)! I’m glad you caught this before we made a release to crates.io. The core dump and/or another pair of eyes to see where we’re going wrong would be very helpful.

**Pull request merged**
